// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lgnowiyptxuyhibptqga.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxnbm93aXlwdHh1eWhpYnB0cWdhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjEyODUzMDQsImV4cCI6MjA3Njg2MTMwNH0.zCqIFPLTEydk1JSbjkK1L4UKrMb4Gwd4rTLb-pXpkMA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});